#!/usr/bin/env bash
# installs nginx and configures it on a remote server

sudo apt update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
