#!/usr/bin/env bash
# Script that installs Nginx server, redirects /redirect_me and customizes 404 not found

######Previous work that got 16.6% - completed 33% checks being 4/5#####################
#sudo apt-get -y update
#sudo apt-get -y install nginx
#sudo ufw allow 'Nginx HTTP'
#echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
#newlines="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
#sudo sed -i "27i $newlines" /etc/nginx/sites-available/default
#sudo service nginx restarti

# correction of the above code that sets up a new 404 error page
sudo apt-get update
sudo apt-get install -y nginx 
echo "Hello World!" > index.html
sudo mv index.html /var/www/html


echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   
   root /var/www/html;
   index index.html;
   location /redirect_me {
      return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
   error_page 404 /404.html;
   location = /404.html{
      internal;
   }
}" > default
sudo mv -f default /etc/nginx/sites-available/default
sudo service nginx restart
