#!/usr/bin/env bash

# Check if the script is run with root privileges
if [ "$EUID" -ne 0 ]; then
  echo "This script must be run as root. Please use sudo."
  exit 1
fi

# Install Nginx if it's not already installed
apt-get update
apt-get install -y nginx

# Set up custom HTML file with "Hello World!"
cat <<EOF > /var/www/html/index.html
<!DOCTYPE html>
<html>
<head>
<title>Hello World</title>
</head>
<body>
<h1>Hello World!</h1>
</body>
</html>
EOF

# Set up custom 404 page with "Ceci n'est pas une page"
cat <<EOF > /var/www/html/404.html
Ceci n'est pas une page
EOF

# Ensure Nginx is stopped before making any configuration changes
service nginx stop

# Configure Nginx to listen on port 80 and set up custom 404 page
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80;
    server_name _;
    add_header X-Served-By \$hostname;

    location / {
        root /var/www/html;
        index index.html;
       }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;

    location /404 {
        root /var/www/html;
        internal;
    }
}
EOF

# Start Nginx
nginx

echo "Nginx is now running and listening on port 80 with custom 404 page set up."
