#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" > sudo /var/www/html/index.html
sudo echo "Ceci n'est pas une page" > sudo /var/www/html/404.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/rky-ke permanent;\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf
sudo service nginx start
