#!/usr/bin/env bash
# Instal and setup haproxy
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8.\*

echo "
frontend www-http
	bind *:80
	mode http
	default_backend web-backend

backend web-backend
	balance roundrobin
	server 126591-web-01 54.84.76.212:80 check
	server 126591-web-02 34.207.212.175:80 check
" >> /etc/haproxy/haproxy.cfg

# Start Ha[proxy Server
service haproxy start

