#!/usr/bin/env bash
# Instal and setup haproxy
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install haproxy=2.8.\*

echo "
frontend www-http
	bind *:80
	mode http
	default_backend web-backend

backend web-backend
	balance roundrobin
	server 126591-web-01 54.84.76.212:80 check
	server 126591-web-02 34.207.212.175:80 check
" >> /etc/haproxy/haproxy.cfg

# Check if HAProxy is running
if systemctl is-active --quiet haproxy; then
    # HAProxy is running, reload the service
    service haproxy reload
else
    # HAProxy is not running, start the service
    service haproxy start
fi

